from enum import Enum


class ImageLabel(str, Enum):
    FRENTE = "FRENTE"
    ATRAS = "ATRAS"
    LATERAL_IZQUIERDA = "LATERAL_IZQUIERDA"
    LATERAL_DERECHA = "LATERAL_DERECHA"
    FRENTE_IZQUIERDA = "FRENTE_IZQUIERDA"
    FRENTE_DERECHA = "FRENTE_DERECHA"
    ATRAS_IZQUIERDA = "ATRAS_IZQUIERDA"
    ATRAS_DERECHA = "ATRAS_DERECHA"
    OTRO = "OTRO"