from enum import Enum


class ImageDetailType(str, Enum):
    ABOLLADURA = "ABOLLADURA"
    VIDRIO_ROTO = "VIDRIO_ROTO"
    RAYON = "RAYON"
    GRIETA = "GRIETA"
    ROTO = "ROTO"
    OXIDO = "OXIDO"
    CALCOMANIA = "CALCOMANIA"
    PIEZA_FALTANTE = "PIEZA_FALTANTE"
    DANO_PINTURA = "DANO_PINTURA"
    DEFORMACION = "DEFORMACION"
    OTRO_COLOR = "OTRO_COLOR"
    OTRO = "OTRO"